"""Add property for 'GO-Anträge' to applicationtype

Revision ID: 0dd00d4bfef5
Revises: 2a7cca8b548e
Create Date: 2024-01-13 12:04:39.934362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd00d4bfef5'
down_revision: Union[str, None] = '2a7cca8b548e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicationtype', sa.Column('goIsAllowed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicationtype', 'goIsAllowed')
    # ### end Alembic commands ###
